# Generated by Django 2.2 on 2019-08-07 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangoStarter', '0002_auto_20190807_1019'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
